spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotmart
    password: postgres
    username: postgres
  jpa:
    show-sql: true
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: create.sql